swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /optimise-task/add:
    post:
      tags:
      - "optimise"
      summary: ""
      description: ""
      operationId: "addTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/OptimseTask"
      responses:
        "200":
          description: "ok"
        "500":
          description: "Invalid input"

definitions:
  OptimseTask:
    type: "object"
    x-annotations:
      - "@NoArgsConstructor"
      - "@AllArgsConstructor"
      - "@EqualsAndHashCode"
      - "@ToString"
      - "@Builder(toBuilder = true)"
    x-imports:
      "lombok.*"
    properties:
      requestKey:
        type: "string"
      usrId:
        type: "string"
      taskId:
        type: "string"
      startTime:
        type: "integer"
        format: "int64"
      approvTime:
        type: "integer"
        format: "int64"
      splice:
        type: "integer"
        format: "int32"
      pceInstance:
        type: "string"
      stateEum:
        type: "string"
        enum:
          - "available"
          - "pending"
          - "sold"
      downloadingProgress:
        type: "integer"
        format: "int32"